// ======================================================================
// \title  MathSender.template.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for MathSender component implementation class
// ======================================================================

#include "Components/MathSender/MathSender.hpp"
#include "FpConfig.hpp"

namespace MathModule {

  // ----------------------------------------------------------------------
  // Component construction and destruction
  // ----------------------------------------------------------------------

  MathSender ::
    MathSender(const char* const compName) :
      MathSenderComponentBase(compName)
  {

  }

  MathSender ::
    ~MathSender()
  {

  }

  // ----------------------------------------------------------------------
  // Handler implementations for user-defined typed input ports
  // ----------------------------------------------------------------------

  void MathSender ::
    mathResultIn_handler(
        NATIVE_INT_TYPE portNum,
        F32 result
    )
  {
    // TODO
  }

  // ----------------------------------------------------------------------
  // Handler implementations for commands
  // ----------------------------------------------------------------------

  void MathSender ::
    DO_MATH_cmdHandler(
        FwOpcodeType opCode,
        U32 cmdSeq,
        F32 val1,
        MathModule::MathOp op,
        F32 val2
    )
  {
    // TODO
    this->cmdResponse_out(opCode, cmdSeq, Fw::CmdResponse::OK);
  }

}
